// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {parser} from '../models';

export function ChooseFile():Promise<string>;

export function RetrieveFileContents(arg1:string):Promise<parser.ParsedContent>;

export function TransposeDownOneStep(arg1:parser.ParsedContent):Promise<parser.ParsedContent>;

export function TransposeUpOneStep(arg1:parser.ParsedContent):Promise<parser.ParsedContent>;
