// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile() {
  return window['go']['main']['App']['ChooseFile']();
}

export function RetrieveFileContents(arg1) {
  return window['go']['main']['App']['RetrieveFileContents'](arg1);
}
