// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseFile():Promise<string>;

export function RetrieveFileContents(arg1:string):Promise<string>;
